services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.33.0
    ports:
      - 8000:8000
      - 9443:9443
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.docker-1.gwebs.ca`) || Host(`portainer.docker-2.gwebs.ca`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=le"
      - "traefik.http.routers.portainer-insecure.rule=Host(`portainer.docker-1.gwebs.ca`) || Host(`portainer.docker-2.gwebs.ca`)"
      - "traefik.http.routers.portainer-insecure.entrypoints=web"
      - "traefik.http.routers.portainer-insecure.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.services.portainer.loadbalancer.server.scheme=http"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true

volumes:
  portainer_data:
